Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 49, in main
    dataloader.loader_set, dataloader.loader)
  File "/home/grupo03/M5/Code/tasks/simple_trainer_manager.py", line 85, in start
    self.training_loop(epoch, train_loader, epoch_bar)
  File "/home/grupo03/M5/Code/tasks/simple_trainer_manager.py", line 118, in training_loop
    for i, data in enumerate(train_loader):
  File "/home/grupo03/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/grupo03/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/grupo03/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/grupo03/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/grupo03/.local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 207, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/home/grupo03/.local/lib/python2.7/site-packages/torch/storage.py", line 122, in _new_shared
    return cls._new_using_fd(size)
RuntimeError: could not unlink the shared memory file /torch_30800_1065517322

