Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 23, in main
    model.build()
  File "/home/grupo03/M5/Code/models/model_builder.py", line 110, in build
    self.net.restore_weights(os.path.join(self.cf.input_model_path))
  File "/home/grupo03/anaconda3/lib/python2.7/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'UNet' object has no attribute 'restore_weights'
